dist: trusty
language: node_js
before_install:
  - git submodule update --init --recursive
node_js:
  - "10"
  - "12"
  - "13"
  - "14"
  - "18"
os:
  - osx
  - linux

matrix:
  include:
    - os: windows
      node_js: "14"
    - os: windows
      node_js: "10"
    - os: windows
      node_js: "12"
    - os: windows
      node_js: "13"
    - os: windows
      node_js: "18"
  allow_failures:
    - os: windows
      node_js: "14"
    - os: windows
      node_js: "10"
    - os: windows
      node_js: "12"
    - os: windows
      node_js: "13"
    - os: windows
      node_js: "18"
  fast_finish: true

script: npm run-script travis
